batch_size: 64
height: 45
learning_rate: 0.001
max_text_length: 6
model_path: Models/02_captcha_to_text/202404031356
train_epochs: 1000
train_workers: 20
vocab: 2d8XY5CFiUlDakjqG0BzvOPKgMI47RtfpewnA9NxQZSy31ETmWhuLHrbcs6oJV
width: 127
