batch_size: 64
height: 45
learning_rate: 0.001
max_text_length: 6
model_path: Models/02_captcha_to_text/202404031850
train_epochs: 1000
train_workers: 20
vocab: 8wfqd3bryaju17plo5h4zx60nksgcev2itm9
width: 127
