batch_size: 64
height: 45
learning_rate: 0.001
max_text_length: 6
model_path: Models/02_captcha_to_text/202404031805
train_epochs: 10
train_workers: 20
vocab: l4W0hX7Zw9d2YKy6UaTHPoSxJ8ucVpAmngBtOGifNR1bzrQ3LFE5eMIDksCjqv
width: 127
